name: Docker Image Push

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: |
        docker build --build-arg VERSION=${GITHUB_REF/refs\/tags\//} . --file Dockerfile --tag openencoder:latest
        docker tag openencoder alfg/openencoder:latest
        docker login docker.pkg.github.com --username alfg --password ${{ secrets.TOKEN }}
        docker tag openencoder docker.pkg.github.com/alfg/openencoder/openencoder:${GITHUB_REF/refs\/tags\//}
        docker push docker.pkg.github.com/alfg/openencoder/openencoder:${GITHUB_REF/refs\/tags\//}
