name: Docker Image Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag openencoder:latest
        docker tag openencoder alfg/openencoder:latest
        docker login docker.pkg.github.com --username alfg --password ${{ secrets.TOKEN }}
        docker tag openencoder docker.pkg.github.com/alfg/openencoder/openencoder:latest
        docker push docker.pkg.github.com/alfg/openencoder/openencoder:latest
